name: build X64
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - name: msvc
      uses: microsoft/setup-msbuild@v2

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      
    - name: script
      shell: cmd
      run: curl -o build.bat https://raw.githubusercontent.com/ikas-mc/wiliwili-uwp-poc/main/build-ci.bat

    - name: build
      shell: cmd
      run: build.bat

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: wiliwili-uwp-X64
        path: |
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.msixbundle
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.msix
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.appx
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.cer
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\Dependencies\x64\*
