name: build X64
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env: 
      USERNAME: ikas-mc
      FEED_URL: https://nuget.pkg.github.com/ikas-mc/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/ikas-mc/index.json,readwrite"

    steps:
    - name: msvc
      uses: microsoft/setup-msbuild@v2

    - name: Add NuGet sources
      shell: pwsh
      run: |
        .$(vcpkg.exe fetch nuget) `
          sources add `
          -Source "${{ env.FEED_URL }}" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ env.USERNAME }}" `
          -Password "${{ secrets.GH_PACKAGES_TOKEN }}"
        .$(vcpkg.exe fetch nuget) `
          setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" `
          -Source "${{ env.FEED_URL }}"
          
    - name: script
      shell: cmd
      run: curl -o build.bat https://raw.githubusercontent.com/ikas-mc/wiliwili-uwp-poc/main/build-ci.bat

    - name: build
      shell: cmd
      run: build.bat

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: wiliwili-uwp-X64
        path: |
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.msixbundle
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.msix
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.appx
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\*.cer
          ${{github.workspace}}\wiliwili-uwp-poc\build\AppPackages\wiliwili-uwp\*\Dependencies\x64\*
